music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
   
 
  
    url(r'^create_trip/$', views.create_trip, name='create_trip'),
   
    url(r'^(?P<trip_id>[0-9]+)/favorite_trip/$', views.favorite_trip, name='favorite_trip'),
    url(r'^(?P<trip_id>[0-9]+)/delete_trip/$', views.delete_trip, name='delete_trip'),
]

music/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class Trip(models.Model):
    user = models.ForeignKey(User, default=1)
    trip_source = models.CharField(max_length=250)
    trip_dest= models.CharField(max_length=250)
    vehicle = models.CharField(max_length=250)
    date = models.DateField()
    amount = models.IntegerField()

    def __str__(self):
        return self.trip_source + ' - ' + self.trip_dest

music/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Trip


class TripForm(forms.ModelForm):

    class Meta:
        model = Trip
        fields = ['trip_source', 'trip_dest' , 'date' , 'vehicle' , 'amount']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import TripForm,UserForm
from .models import Trip



def create_trip(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        form = TripForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            trip = form.save(commit=False)
            trip.user=request.user
            trip.save()
            trips = Trip.objects.filter(user=request.user)
            return render(request, 'music/index.html', {'trip': trips})
        context = {
            "form": form,
        }
        return render(request, 'music/create_trip.html', context)


def delete_trip(request, trip_id):
    trip = Trip.objects.get(pk=trip_id)
    trip.delete()
    trips = Trip.objects.filter(user=request.user)
    return render(request, 'music/index.html', {'trip': trips})



def favorite_trip(request, trip_id):
    trip = get_object_or_404(Trip, pk=trip_id)
    try:
        if trip.is_favorite:
            trip.is_favorite = False
        else:
            trip.is_favorite = True
        trip.save()
    except (KeyError, Trip.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        trip = Trip.objects.filter(user=request.user)
        trips=Trip.objects.all()
        query = request.GET.get("q")
        query1=request.GET.get("y")
        if query and query1:
            trips = trips.filter(
                Q(trip_source__icontains=query) &
                Q(trip_dest__icontains=query1)
            ).distinct()
            return render(request, 'music/index.html', {
                'trips': trips,
                
            })
        elif query:
            trips = trips.filter(
                Q(trip_source__icontains=query) 
                
            ).distinct()
            return render(request, 'music/index.html', {
                'trips': trips,
                
            })
        elif query1:
            trips = trips.filter(
                Q(trip_dest__icontains=query1) 
               
            ).distinct()
          
            return render(request, 'music/index.html', {
                'trips': trips,
                
            })
        else:
            return render(request, 'music/index.html', {'trip': trip})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'music/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                trips = Trip.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'trip': trips})
            else:
                return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    return render(request, 'music/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                trips = Trip.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'trips': trips})
    context = {
        "form": form,
    }
    return render(request, 'music/register.html', context)

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Travel Mate{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Travel Mate</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block trips_active %}{% endblock %}"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Trips</a></li>
               
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}" placeholder="Source">
                     <input type="text" class="form-control" name="y" value="{{ request.GET.y }}" placeholder="Destination">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'music:create_trip' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Trip
                    </a>
                </li>
                <li>
                    <a href="{% url 'music:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Travel Mate{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Travel Mate</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/create_album.html
{% extends 'music/base.html' %}
{% block title %}Add a New Trip{% endblock %}
{% block trips_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Trip</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h1> Tripper</h1>
                   
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

music/templates/music/create_trip.html
{% extends 'music/base.html' %}
{% block title %}Add a New Trip{% endblock %}
{% block trips_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Trip</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h1> Tripper</h1>
                   
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block trips_active %}active{% endblock %}

{% block body %}
<div class="trips-container container-fluid">

    <!-- Trips -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Trips</h3>
        </div>
        {% if trips %}
            

            

        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-primary ">
                    <div class="panel-body text-prima">
                        <table class="table">
                            <thead> 
                                <tr>
                                    <th>TripCreator</th>
                                    <th>Source</th>
                                    <th>Destination</th>
                                    <th>Vehicle</th>
                                    <th>Date</th>
                                    <th>Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for tr in trips %}
                                    <tr>
                                        <td>{{tr.user.username}}
                                        <td>{{ tr.trip_source }}</td>
                                        <td>{{ tr.trip_dest }}</td>
                                        <td>{{ tr.vehicle }}</td>
                                        <td>{{tr.date}}</td>
                                        <td>{{tr.amount}}</td>
                                    
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    	{% elif trip %}
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-primary ">
                    <div class="panel-body text-prima">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Source</th>
                                    <th>Destination</th>
                                    <th>Vehicle</th>
                                    <th>Date</th>
                                    <th>Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for tr in trip %}
                                    <tr>
                                        
                                        <td>{{ tr.trip_source }}</td>
                                        <td>{{ tr.trip_dest }}</td>
                                        <td>{{ tr.vehicle }}</td>
                                        <td>{{tr.date}}</td>
                                        <td>{{tr.amount}}</td>
                                         <td>
                                            <form action="{% url 'music:delete_trip' tr.id %}" method="post" style="display: inline;">
                                            {% csrf_token %}
                                                <input type="hidden" name="trip_id" value="{{ trip.id }}" />
                                                <button type="submit" class="btn btn-danger btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:create_trip' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Trip
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
    

</div>
{% endblock %}

music/templates/music/login.html
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Travel Mate</title>

        <!-- CSS -->
        {% load staticfiles %}
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="{% static 'music/assets/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'music/assets/font-awesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'music/assets/css/form-elements.css' %}">
        <link rel="stylesheet" href="{% static 'music/style.css' %}">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="assets/ico/favicon.png">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'music/assets/ico/apple-touch-icon-144-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'music/assets/ico/apple-touch-icon-114-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'music/assets/ico/apple-touch-icon-72-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" href="{% static 'music/assets/ico/apple-touch-icon-57-precomposed.png' %}">

    </head>

    <body>

        <!-- Top content -->
        <div class="top-content">
            
            <div class="inner-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-8 col-sm-offset-2 text">
                            <h1><strong>Travel</strong> Mate</h1>
                            <div class="description">
                                
                            </div>
                        </div>
                    </div>
                   <!-- {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                -->
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3 form-box">
                            <div class="form-top">
                                <div class="form-top-left">
                                    <h3>Login to our site</h3>
                                    <p>Enter your username and password to log on:</p>
                                </div>
                                <div class="form-top-right">
                                    <i class="fa fa-lock"></i>
                                </div>
                            </div>
                            <div class="form-bottom">
                                <form role="form" action="{% url 'music:login_user'%}" method="POST" class="login-form" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    
                                    <div class="form-group">
                                        <label class="sr-only" for="id-username">Username</label>
                                        <input type="text" name="username" class="form-username form-control" placeholder="Username" id="id_username">
                                    </div>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-password">Password</label>
                                        <input type="password" name="password"  class="form-password form-control" placeholder="Password" id="id_password">
                                    </div>
                                    <button type="submit" class="btn">Sign in!</button>
                                   <!-- {% csrf_token %}
                                    <div class="form-group">
                                        <label class="control-label col-sm-2" for="id_username">
                                        Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                                </form>
                                -->
                                
                                <div class= "form-top">
                                    <h4>Not a member?
                                    <a href="{% url 'music:register' %}">sign up</a>
                                    </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
            
        </div>


        <!-- Javascript -->
        <script src="{% static 'music/assets/js/jquery-1.11.1.min.js' %}"></script>
        <script src="{% static 'music/assets/bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'music/assets/js/jquery.backstretch.min.js' %}"></script>
        <script src="/static/music/assets/js/scripts.js"></script>
        
        <!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->

    </body>

</html>

music/templates/music/register.html
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
         <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Travel Mate</title>

        <!-- CSS -->
        {% load staticfiles %}
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="{% static 'music/assets/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'music/assets/font-awesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'music/assets/css/form-elements.css' %}">
        <link rel="stylesheet" href="{% static 'music/style.css' %}">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="assets/ico/favicon.png">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'music/assets/ico/apple-touch-icon-144-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'music/assets/ico/apple-touch-icon-114-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'music/assets/ico/apple-touch-icon-72-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" href="{% static 'music/assets/ico/apple-touch-icon-57-precomposed.png' %}">

    </head>

    <body>

        <!-- Top content -->
        <div class="top-content">
            
            <div class="inner-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-8 col-sm-offset-2 text">
                            <h1><strong>Travel</strong> Mate</h1>
                            <div class="description">
                                
                            </div>
                        </div>
                    </div>
                   <!-- {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                -->
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3 form-box">
                            <div class="form-top">
                                <div class="form-top-left">
                                    <h3>Login to our site</h3>
                                    <p>Enter your username and password to log on:</p>
                                </div>
                                <div class="form-top-right">
                                    <i class="fa fa-lock"></i>
                                </div>
                            </div>
                            <div class="form-bottom">
                               <!-- <form role="form" action="" method="post" class="login-form" enctype="multipart/form-data">
                                    {% csrf_token %}-->
                                     <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% include 'music/form_template.html' %}
                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-success">Submit</button>
                                        </div>
                                        </div>
                                    </form>
                                    <!--<div class="form-group">
                                        <label class="sr-only" for="form-username">Username</label>
                                        <input type="text" name="form-username" placeholder="Username..." class="form-username form-control" id="id_username">
                                    </div>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-password">Password</label>
                                        <input type="password" name="form-password" placeholder="Password..." class="form-password form-control" id="id_password">
                                    </div>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-username">Email</label>
                                        <input type="email" name="form-email" placeholder="    Mail id..." class="form-email form-control" id="id_email">
                                    </div>
                                    <button type="submit" class="btn">Sign up!</button>
                                -->
                                <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="sr-only" for="song_title">{{ field.label_tag }}</label>
        <div class="form-username">{{ field }}</div>
    </div>
                                    
                                </form>
                                <div class= "form-top">
                                    <h4>Already a member?
                                    <a href="{% url 'music:login_user' %}">login</a>
                                    </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
            
        </div>


        <!-- Javascript -->
        <script src="{% static 'music/assets/js/jquery-1.11.1.min.js' %}"></script>
        <script src="{% static 'music/assets/bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'music/assets/js/jquery.backstretch.min.js' %}"></script>
        <script src="/static/music/assets/js/scripts.js"></script>
        
        <!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->

    </body>

</html>